"use client";
import { useEffect, useState } from "react";

const works = [
  ["001qinghuan.webp","清欢","以清醒的温柔，安放尘世的欢喜。"],["002memory.webp","记忆","旧日的光，仍停在眼睛深处。"],["003silence.webp","静默","沉默不是空白，是尚未说出的海。"],["004FallenDream.webp","坠落的梦","梦坠下时，仍保留羽毛的重量。"],["005Forgotten.webp","被遗忘者","遗忘不是消失，而是换一种方式停留。"],["006LastWhisper.webp","最后的低语","有些告别，只能被画成极轻的一笔。"],["007LostTime.webp","遗失的时间","时间离开后，留下了褪色的轮廓。"],["008EternalSleep.webp","永恒睡眠","在漫长的安眠里，灵魂仍在苏醒。"],["009BrokenPromise.webp","破碎的约定","承诺碎裂后，仍有微光折返。"],["010Afterglow.webp","余晖","黑夜收拢前，替温柔多留一瞬。"],["011EmptyHeart.webp","空心","空出来的地方，正等待新的呼吸。"],["012SilentTear.webp","无声之泪","眼泪没有声音，却改变了一切。"],["013DreamFragment.webp","梦的碎片","梦并不完整，才有了回来的路。"],["014FadingMemory.webp","褪色记忆","色彩退去，心事反而变得清晰。"],["015LunarRemains.webp","月之遗痕","月亮经过后，把银色留在裂缝里。"],["016HiddenSoul.webp","隐匿的灵魂","她把自己藏进了花影和雾中。"],["017ColdGarde.webp","冷园","寒意之中，也有一朵花不肯凋零。"],["018LostChild.webp","迷失的孩子","她在找回自己的路上，停下来望了望星星。"],["019DollWithoutaNam.webp","无名娃娃","她没有名字，因此也从未被真正遗忘。"],["020PorcelainHeart.webp","瓷心","她把最脆弱的地方，留给了光。"],["021VelvetNight.webp","丝绒之夜","夜色柔软得像一封没有寄出的信。"],["022Dreamless.webp","无梦","不做梦的夜晚，依然有月光作伴。"],["023FrostMemory.webp","霜之记忆","霜落在往事上，也落在未愈合的心里。"],["024Echo.webp","回声","所有没能说出口的话，都在远处回响。"],["025Vanishing.webp","消隐","她慢慢淡去，却没有真正离开。"],["026NeverAwake.webp","未曾醒来","梦境太深，醒来反而像一种遗失。"],["027AshesOfMemory.webp","记忆余烬","灰烬里藏着火曾经热烈的证据。"],["028SilentKingdom.webp","静默王国","她在自己的王国里，与寂静平分时间。"],["029BeforeDawn.webp","黎明之前","最暗的时刻，也正靠近第一束光。"],["030BlackRoseMemory.webp","黑玫瑰记忆","柔软与枯萎，在同一片夜色里生长。"],["031FaintExistence.webp","微弱存在","即使只剩一丝光，也足够证明来过。"],["032BeyondSilence.webp","越过静默","穿过寂静，才能听见内心真正的声音。"],["033EndlessWinter.webp","无尽冬日","冬天很长，春天却从未缺席。"],["034GlassTears.webp","玻璃眼泪","透明的疼痛，也会折射出颜色。"],["035ForgottenMelody.webp","遗忘的旋律","旋律散去后，心仍记得它的形状。"],["036TheHollowDream.webp","空洞的梦","空洞不是终点，它也能盛住星光。"],["037ForgottenLullaby.webp","遗忘的摇篮曲","所有沉默，终会变成另一种歌声。"]
].filter(([image])=>image!=="020PorcelainHeart.webp").map(([image,name,text])=>({image,name,text}));

export default function Home(){
  const [entered,setEntered]=useState(false); const [assembled,setAssembled]=useState(false); const [selected,setSelected]=useState(0);
  useEffect(()=>{const timer=window.setTimeout(()=>setAssembled(true),2100);return()=>window.clearTimeout(timer)},[]);
  const openWork=(index:number)=>{setSelected(index);document.querySelector("#focus")?.scrollIntoView({behavior:"smooth",block:"start"})};
  if(!entered)return <main className="opening"><div className="shardStage" aria-label="破碎娃娃拼合动画"><img className="wholeDoll" src="/doll.webp" alt="破碎娃娃"/>{["one","two","three","four","five","six","seven","eight"].map(name=><i className={`shard ${name}`} key={name}/>)}</div><div className="openingShade"/><div className={`openingCopy ${assembled?"revealed":""}`}><p>PRIVATE DIGITAL EXHIBITION · 2026</p><h1>BROKEN DOLL</h1><span>破 碎 娃 娃</span><button onClick={()=>setEntered(true)}>进入展览 <b>→</b></button></div></main>;
  const work=works[selected];
  const imageUrl=(image:string)=>`/gallery/${image==="027AshesOfMemory.webp"?"027AshesofMemory.webp":image}`;
  return <main className="museum"><header className="museumNav"><a className="wordmark" href="#top">BROKEN DOLL</a><nav><a href="#letter">作者引言</a><a href="#focus">展馆</a><a href="#archive">作品档案</a><a href="#contact">联系我</a></nav><span>破碎娃娃 · 数字艺术展</span></header>
  <section id="top" className="museumHero"><div className="heroCrackLight" aria-hidden="true"/><p>01 / PRIVATE EXHIBITION</p><h1>每一道裂痕，<br/>都有<em>光</em>经过。</h1><span>SCROLL TO ENTER</span></section>
  <section id="letter" className="letter"><p>作者引言 / 02</p><div><h1>我不修复破碎。<br/>我让它们，<em>被看见。</em></h1><article>“破碎娃娃”不是关于失去的故事。它关乎那些被藏起来的敏感、未被命名的脆弱，以及一颗心如何在裂缝中继续感受。每一幅画，都是一次安静的凝视。<blockquote>不完美又何妨，万物皆有裂隙，那是光进来的地方！</blockquote></article></div></section>
  <section id="focus" className="focus"><div className="sectionLabel"><p>展馆 / 03</p><span>SELECTED WORK · {String(selected+1).padStart(2,"0")}/{String(works.length).padStart(2,"0")}</span></div><div className="focusWork"><img src={imageUrl(work.image)} alt={work.name}/><div className="focusText"><p>破碎娃娃系列 / 油画</p><h2>{work.name}</h2><span>{work.text}</span><div className="focusControls"><button onClick={()=>openWork((selected+works.length-1)%works.length)}>←</button><button onClick={()=>openWork((selected+1)%works.length)}>→</button></div></div></div></section>
  <section id="archive" className="archive"><div className="archiveIntro"><p>作品档案 / 04</p><h2>三十六次<br/><em>安静的凝视</em></h2><span>作品会持续增加。这里不是图库，而是一座仍在生长的私人展馆。</span></div><div className="workGrid">{works.map((item,index)=><button className={index===selected?"active":""} onClick={()=>openWork(index)} key={item.image}><img src={imageUrl(item.image)} alt={item.name}/><i>{String(index+1).padStart(2,"0")}</i><strong>{item.name}</strong><small>{item.text}</small></button>)}</div></section>
  <section id="contact" className="contact"><p>联系我 / 05</p><h1>让一件作品，<br/><em>找到它的目光。</em></h1><div className="contactBox"><img src="/douyin-qr.png" alt="清欢抖音二维码"/><div><strong>@清欢👑</strong><span>抖音号 · 171330823</span><small>扫码进入我的抖音主页</small></div></div><footer>© 2026 BROKEN DOLL · 清欢</footer></section></main>
}
